blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
	url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^user/author/(?P<pk>\d+)/$', views.author_details, name='author_details'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls')),
    url(r'', include('techlab.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

techlab/urls.py
from django.conf.urls import url
from . import views

app_name = 'techlab'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^techlab/about/$', views.about, name='about'),
    url(r'^techlab/contact/$', views.contact, name='contact'),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','text')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse


def post_list(request):
    posts = Post.objects.exclude(published_date__isnull=True).order_by('-published_date')
    context = {
        'posts':posts,
    }
    return render(request, 'blog/post_list.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/blog-post.html', {'post': post})


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_draft_list')
    else:
        form = PostForm()
        return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_draft_list')
    else:
        form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_draft_list(request):
    user = request.user
    posts = Post.objects.all().filter(author=user).order_by('-created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_draft_list')


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_draft_list')


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            comment = form.save(commit=False)
            comment.post = post
            comment.author = form.cleaned_data['author']
            comment.text = form.cleaned_data['text']
            comment.created_date = timezone.now()
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})



@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

def author_details(request, pk):
    return HttpResponse(pk)

techlab/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'techlab/index.html')

def about(request):
	return render(request, 'techlab/about.html')

def contact(request):
	return render(request, 'techlab/contact.html')

blog/templates/blog/add_comment_to_post.html
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <script src="{% static 'js/custome_js.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- main content -->
    <div class="container-fluid" style="margin-top: 60px;">
      <div class="row profile">
    		<div class="col-md-3" style="">
    			<div class="profile-sidebar">
            {% if user.is_authenticated %}
    				<div class="profile-userpic">
    					<img src="{% static 'images/1.png' %}" class="img-responsive" alt="">
    				</div>
    				<div class="profile-usertitle">
    					<div class="profile-usertitle-name">
    						{{ user }}
    					</div>
    					<div class="profile-usertitle-job">
    						Developer
    					</div>
    				</div>
    				<div class="profile-userbuttons">
    					<button type="button" class="btn btn-success btn-sm">Follow</button>
    					<button type="button" class="btn btn-danger btn-sm">Message</button>
    				</div>
            {% endif %}
    				<div class="profile-usermenu">
    					<ul class="nav">
                <li class="">
                  <a href="#">CATEGORIES </a>
                </li>
    						<li class="active">
    							<a href="#">
    							<i class="glyphicon glyphicon-home"></i>
    							HTML </a>
    						</li>
                <li>
                  <a href="#" target="_blank">
                  <i class="glyphicon glyphicon-ok"></i>
                  PHP </a>
                </li>
                <li>
                  <a href="#">
                  <i class="glyphicon glyphicon-flag"></i>
                  Help </a>
                </li>
                {% if user.is_authenticated %}
      						<li>
      							<a href="#">
      							<i class="glyphicon glyphicon-user"></i>
      							Account Settings </a>
      						</li>
                  <li class="">
                    <a href="#">
                    <i class="glyphicon glyphicon-home"></i>
                    My Post </a>
                  </li>
                  <li class="">
                    <a href="{% url 'blog:post_new' %}">
                    <i class="glyphicon glyphicon-home"></i>
                    Create Post </a>
                  </li>
                {% endif %}
    					</ul>
    				</div>
    			</div>
    		</div>

        {% block content %}

        {% endblock %}
      </div>
      </div>
    </div>
</body>
</html>

blog/templates/blog/blog-post.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-md-9" style="background-color: #fff;">
  <ol class="breadcrumb">
    <li><a href="{% url 'blog:post_list' %}">Home</a></li>
    <li class="active">blog post</li>
  </ol>
  <div class="row">
      <div class="[ col-xs-12 col-sm-12 ]">
            <div class="[ panel panel-default ] panel-google-plus">
                <div class="panel-heading">
                    <img class="[ img-circle pull-left ]" src="https://lh3.googleusercontent.com/-CxXg7_7ylq4/AAAAAAAAAAI/AAAAAAAAAQ8/LhCIKQC5Aq4/s46-c-k-no/photo.jpg" alt="Mouse0270" />
                    <h3>{{ post.author }}</h3>
                    <h5><span>Shared publicly</span> - <span>{{ post.published_date }}</span> </h5>
                </div>
                <hr>
                <div class="panel-body">
                    <p class="lead">{{ post.title }}</p>
                    <p>{{ post.text|linebreaksbr }}</p>
                    <h4>Post Images</h4>
                    <hr>
                    	<div class="row">
                    		<div class="col-md-4 col-sm-4 col-xs-6">
                          <img class="img-responsive" src="{% static 'images/1.png' %}" />
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                          <img class="img-responsive" src="{% static 'images/1.png' %}" />
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                          <img class="img-responsive" src="{% static 'images/1.png' %}" />
                        </div>
                      </div>
                </div>
                <div class="panel-footer">
                    <button type="button" class="[ btn btn-default ]">+1</button>
                    <button type="button" class="[ btn btn-default ]">
                        <span class="[ glyphicon glyphicon-share-alt ]"></span>
                    </button>
                    <div class="input-placeholder">Add a comment...</div>
                </div>
                <div class="panel-google-plus-comment">
                    {# <img class="img-circle" src="https://lh3.googleusercontent.com/uFp_tsTJboUY7kue5XAsGA=s46" alt="User Image" /> #}
                    <div class="panel-google-plus-textarea">
                        <form action="{% url 'blog:add_comment_to_post' pk=post.pk %}" method="post">
                          {% csrf_token %}
                          <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="author" class="form-control" required>
                          </div>
                          <label for="comment">Comment</label>
                          <div class="form-group">
                            <textarea class="form-control" name="text" rows="1" style="resize: none;"></textarea>
                          </div>
                          <button type="submit" class="[ btn btn-success disabled ]">Post comment</button>
                          <button type="reset" class="[ btn btn-default ]">Cancel</button>
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
  </div>
  <div class="col-lg-12">
     <!-- Single Comment -->
     <div class="card mb-4" id="comment_card">
       <div class="card-header">
         <h6 class="card-title">Comments By users</h6>
       </div>
       <div class="card-body">
         {% for comment in post.comments.all %}
          <!-- user is not authenticated -->
          {% if not user.is_authenticated %}
          <!-- show only approved comments -->
            {% if comment.approved_comment %}
            <div class="row">
              <div class="col-md-3" style="max-width: 5%;">
                <img src="{% static 'images/1.png' %}" width="40" alt="">
              </div>
              <div class="col-md-6">
                <strong>{{ comment.author }}</strong>
                {{ comment.text|linebreaks }}
                {{ comment.created_date }}
              </div>
            </div>
            <hr>
            {% endif %}
          {% else %}
          <!-- use is authenticated -->
            <div class="row">
              <div class="col-md-3" style="max-width: 5%;">
                <img src="{% static 'images/1.png' %}" width="40" alt="">
              </div>
              <div class="col-md-6">
                <strong>{{ comment.author }}</strong>
                {{ comment.text|linebreaks }}
                {{ comment.created_date }}
              </div>
              <div class="col-md-3">
                <!-- show controls for unapproved comments -->
                {% if not comment.approved_comment %}
                  <a href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve</a> |
                  <a href="{% url 'blog:comment_remove' pk=comment.pk %}">Remove</a>
                {% endif %}
              </div>
            </div>
            <hr>
          {% endif %}
        {% empty %}
           <p class="text-center">No comments here yet :(</p>
        {% endfor %}
        </div>
     </div>
   </div>
 </div>
 </div>
 {% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-md-9" style="background-color: #fff;">
  <div class="row">
    <div class="col-md-10">
    {% if posts.count > 0 %}
    {% for post in posts %}
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-9">
              <p class="lead">{{ post.title }}</p>
              <p class="post">{{ post.text|lower|truncatewords:'25' }}<a href="{% url 'blog:post_detail' post.id %}">read more</a></p>
            </div>
            <div class="col-md-3" style="padding: 10px;">
              <img class="img-fluid rounded" width="100" src="{% static 'images/1.png' %}" alt="">
            </div>
          </div>

        </div>
          {% if post.published_date %}
          <div class="card-footer">
            <span class="text-primary" style="padding: 5px;">Posted on {{ post.published_date }}</span>
            <span class="text-primary" style="padding: 5px;">Created On {{ post.created_date }}</span>
          </div>
          <div class="card-footer">
            <a class="btn btn-primary btn-sm" href="{% url 'blog:post_edit' pk=post.pk %}">
                edit
            </a>
            <a class="btn btn-danger btn-sm" href="{% url 'blog:post_remove' pk=post.pk %}">
                delete
            </a>
          </div>
          {% else %}
          <div class="card-footer">
            <span class="text-primary" style="padding: 5px;">Created On {{ post.created_date }}</span>
          </div>
          <div class="card-footer">
            <a class="btn btn-primary btn-sm" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
            <a class="btn btn-primary btn-sm" href="{% url 'blog:post_edit' pk=post.pk %}">
                edit
            </a>
            <a class="btn btn-danger btn-sm" href="{% url 'blog:post_remove' pk=post.pk %}">
                delete
            </a>
          </div>
          {% endif %}
        </div>
      <br>
      {% endfor %}
      {% else %}
      <div class="alert alert-info text-center">
        <h4>You have not created any post yet</h4>
      </div>
    {% endif %}
  </div>
  <div class="col-md-2"></div>
</div>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
<div class="col-md-9" style="background-color: #fff;">
  <div class="panel panel-info" style="border-color: #fff;">
    <div class="panel-heading">
      <h4>New post</h4>
    </div>
    <div class="panel-body">
      <form method="POST" class="post-form">
          {% csrf_token %}
          <div class="form-group">
            <label for="title">Title</label>
            {% render_field form.title class="form-control"%}
          </div>
          <div class="form-group">
            <label for="title">body</label>
            {% render_field form.text class="form-control"%}
          </div>
          <div class="form-group">
            <button type="submit" class="save btn btn-success">Save</button>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="col-md-9" style="background-color: #fff;">
  {% if posts.count > 0 %}
    {% for post in posts %}
    <div class="row">
        <div class="col-md-12 post">
            <div class="row">
                <div class="col-md-12">
                    <h4>
                        <strong>
                          <a href="" class="post-title">{{ post.title }}</a>
                        </strong>
                      </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 post-header-line">
                    <span class="glyphicon glyphicon-user"></span>by <a href="#">{{ post.author }}</a> | <span class="glyphicon glyphicon-calendar">
                    </span>{{ post.published_date }} | <span class="glyphicon glyphicon-comment"></span><a href="#">
                        {{ post.comments.count }} Comments</a> | <i class="icon-share"></i><a href="#">39 Shares</a> | <span class="glyphicon glyphicon-tags">
                        </span>Tags : <a href="#"><span class="label label-info">Snipp</span></a> <a href="#">
                            <span class="label label-info">Bootstrap</span></a> <a href="#"><span class="label label-info">
                                UI</span></a> <a href="#"><span class="label label-info">growth</span></a>
                </div>
            </div>
            <div class="row post-content">
                <div class="col-md-3">
                    <a href="#">
                        <img src="{% static 'images/1.png' %}" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="col-md-9">
                    <p>{{ post.text|lower|truncatewords:'35' }}</p>
                    <p>
                      <a class="btn btn-read-more" href="{% url 'blog:post_detail' pk=post.pk %}">Read more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}

  {% endif %}
{% endblock %}

techlab/templates/techlab/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Techlab - Home</title>
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="margin-bottom: 0px">
      <a class="navbar-brand" href="#"><img src="{% static 'images/logo.png' %}" alt="techlab logo" style="height: 50px;"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'techlab:index' %}">
                <i class="fa fa-home"></i>
                Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'techlab:about'%}">
              <i class="fa fa-question-circle"></i>
              About
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'techlab:contact' %}">
              <i class="fa fa-phone-square"></i>
              Contact
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Apps
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="row">
                <div class="col-lg-4">
                  <div class="card h-100" id="apps">
                    <a href="{% url 'blog:post_list'%}">
                      <div class="card-body">
                         <img src="{% static 'images/blog-circle.png' %}" alt="" style="height: 100px; Width: 100px;">
                         <h4 class="card-title text-muted">Blog</h4>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="card h-100" id="apps">
                    <div class="card-body">
                       <img src="{% static 'images/forum.png' %}" alt="" style="height: 100px; Width: 100px;">
                       <h4 class="card-title text-muted">Forum</h4>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="card h-100" id="apps">
                    <div class="card-body">
                      <img src="{% static 'images/education.png' %}" alt="" style="height: 100px; Width: 100px;">
                      <h4 class="card-title text-muted">Education</h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" size="50" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </nav>
    {% block partial %}
      <header id="carousel">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url({% static 'images/1.png' %})">
            <div class="carousel-caption d-none d-md-block">
              <h3>First Slide</h3>
              <p>This is a description for the first slide.</p>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url({% static 'images/2.jpg' %})">
            <div class="carousel-caption d-none d-md-block">
              <h3>Second Slide</h3>
              <p>This is a description for the second slide.</p>
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url({% static 'images/3.jpg' %})">
            <div class="carousel-caption d-none d-md-block">
              <h3>Third Slide</h3>
              <p>This is a description for the third slide.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>
    {% endblock %}
    <!-- Page Content -->
    <div class="container" id="main_content">
      {% block content %}
      {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
      </div>
    </footer>
    <footer class="py-5" id="footer_bottom">
      <div class="container">
        <p class="m-0 text-white">
          &copy; Copyright  techlab.com 2018
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript">
      $('#navbarDropdownPortfolio').click(function(){
        $('#list_of_apps').slideToggle();
      })
    </script>
  </body>

</html>